const baseUrl = "https://amezone-clone-sarver-4.onrender.com";
//base url for localhost
//const baseUrl = "http://10.0.2.2:3000";
const signUpUrl = "/api/signup";
const signInUrl = "/api/signin";
const tokenIsValid = "/tokenIsValid";
const updateProfile = "/api/user/update";
const updateStatus = "/api/status";
const nearbyuser = "/api/nearbyusers";
const saveChat = "/api/messages";
const chatUsers = "/api/user/chats";
const getChat = "/api/chats";
const fcmToken = "/api/fcmToken";
